# Generated by Django 4.2.3 on 2023-07-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0002_conta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="banco",
            field=models.CharField(
                choices=[
                    ("NU", "Nubank"),
                    ("CE", "Caixa economica"),
                    ("PS", "PagSeguro"),
                    ("MP", "Mercado Pago"),
                    ("BB", "Banco Brasil"),
                    ("BI", "Banco Itau"),
                ],
                max_length=2,
            ),
        ),
    ]
